In [1]:
import torch

In [2]:
# simple operation rehash
u = torch.tensor([2, 4])
v = torch.tensor([1, 4])
w = u * v
print(w)
print(w.shape)
print(w.ndim)

tensor([ 2, 16])
torch.Size([2])
1


In [3]:
# broadcasting rules 
a =     torch.ones(4, 3, 2)
b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

tensor([[[0.9163, 0.7987],
         [0.7952, 0.5068],
         [0.6698, 0.1389]],

        [[0.9163, 0.7987],
         [0.7952, 0.5068],
         [0.6698, 0.1389]],

        [[0.9163, 0.7987],
         [0.7952, 0.5068],
         [0.6698, 0.1389]],

        [[0.9163, 0.7987],
         [0.7952, 0.5068],
         [0.6698, 0.1389]]])


In [4]:
c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

tensor([[[0.2207, 0.2207],
         [0.7917, 0.7917],
         [0.2368, 0.2368]],

        [[0.2207, 0.2207],
         [0.7917, 0.7917],
         [0.2368, 0.2368]],

        [[0.2207, 0.2207],
         [0.7917, 0.7917],
         [0.2368, 0.2368]],

        [[0.2207, 0.2207],
         [0.7917, 0.7917],
         [0.2368, 0.2368]]])


In [5]:
d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.9508, 0.0776],
         [0.9508, 0.0776],
         [0.9508, 0.0776]],

        [[0.9508, 0.0776],
         [0.9508, 0.0776],
         [0.9508, 0.0776]],

        [[0.9508, 0.0776],
         [0.9508, 0.0776],
         [0.9508, 0.0776]],

        [[0.9508, 0.0776],
         [0.9508, 0.0776],
         [0.9508, 0.0776]]])


In [6]:
# switch between ndarrays and PyTorch tensors
import numpy as np
numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
# reverse example of converting from PyTorch tensor into ndarray
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.7758, 0.6925, 0.3645],
        [0.0519, 0.7584, 0.1977]])
[[0.77578497 0.6925213  0.36446184]
 [0.05190009 0.75843173 0.19771397]]


In [8]:
# using the same underlying memory
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.77578497  0.6925213   0.36446184]
 [ 0.05190009 17.          0.19771397]]
