In [ ]:
# require gradient on a variable 

In [1]:
import torch
from torch.autograd import Variable

In [2]:
x = torch.randn(3)
x = Variable(x, requires_grad=True)
print(x)

tensor([-0.1109, -1.1387, -0.7953], requires_grad=True)


In [3]:
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([ -113.5576, -1165.9904,  -814.3569], grad_fn=<MulBackward0>)


In [4]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)

In [5]:
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [6]:
# Fronzen parameters 

In [7]:
from torch import nn, optim
import torchvision

In [8]:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

In [9]:
model = torchvision.models.resnet18(pretrained=True)

In [10]:
# Freeze all the parameters in the network
for param in model.parameters():
    param.requires_grad = False

In [11]:
model.fc = nn.Linear(512, 10)

In [12]:
# Optimize only the classifier
optimizer = optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [13]:
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.01
    momentum: 0.9
    nesterov: False
    weight_decay: 0
)
