In [1]:
import torch

In [2]:
# create some tensors
t0 = torch.tensor(1000)                     # 0-D tensor
t1 = torch.tensor([9, 8, 7, 6])             # 1-D tensor
t2 = torch.tensor([[1, 2, 3], [7, 5, 3]])   # 2-D tensor

print(t0)
print(t1)
print(t2)

tensor(1000)
tensor([9, 8, 7, 6])
tensor([[1, 2, 3],
        [7, 5, 3]])


In [3]:
# set datatype for the tensor
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [4]:
""" Tensor data types
torch.bool
torch.int8
torch.uint8
torch.int16
torch.int32
torch.int64
torch.half
torch.float
torch.double
torch.bfloat
"""

' Tensor data types\ntorch.bool\ntorch.int8\ntorch.uint8\ntorch.int16\ntorch.int32\ntorch.int64\ntorch.half\ntorch.float\ntorch.double\ntorch.bfloat\n'

In [5]:
# get the tensor size
print(a.size())
print(a.shape)

torch.Size([2, 3])
torch.Size([2, 3])


In [6]:
# get the tensor dimension
print(a.ndimension())
print(a.ndim)

2
2
