# 1.

In [ ]:
import torch
import numpy as np
import torch.nn as nn
import torch.optim as optim

In [ ]:
dataset = np.loadtxt(r"C:\Users\Slmss\OneDrive\Desktop\A.I. Factory\DataSet-main\PIMA_INDIANS_DIABETES_CSV_DATASETS-main\pima-indians-diabetes.csv", delimiter=',')
X = dataset[:,0:8]
y = dataset[:,8]

In [ ]:

X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32).reshape(-1, 1)

In [ ]:
model = nn.Sequential(
    nn.Linear(8, 12),
    nn.ReLU(),
    nn.Linear(12, 8),
    nn.ReLU(),
    nn.Linear(8, 1),
    nn.Sigmoid())

In [ ]:
print(model)

In [ ]:
...
 
class PimaClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden1 = nn.Linear(8, 12)
        self.act1 = nn.ReLU()
        self.hidden2 = nn.Linear(12, 8)
        self.act2 = nn.ReLU()
        self.output = nn.Linear(8, 1)
        self.act_output = nn.Sigmoid()
 
    def forward(self, x):
        x = self.act1(self.hidden1(x))
        x = self.act2(self.hidden2(x))
        x = self.act_output(self.output(x))
        return x
 
model = PimaClassifier()
print(model)

In [ ]:
loss_fn   = nn.BCELoss()  # binary cross entropy
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [ ]:
n_epochs = 100
batch_size = 10
 
for epoch in range(n_epochs):
    for i in range(0, len(X), batch_size):
        Xbatch = X[i:i+batch_size]
        y_pred = model(Xbatch)
        ybatch = y[i:i+batch_size]
        loss = loss_fn(y_pred, ybatch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    print(f'Finished epoch {epoch}, latest loss {loss}')

In [ ]:

# compute accuracy (no_grad is optional)
with torch.no_grad():
    y_pred = model(X)
 
accuracy = (y_pred.round() == y).float().mean()
print(f"Accuracy {accuracy}")

# 2.

In [2]:
import numpy as np
import torch

In [34]:
x=[i for i in range(100)]
end=3

X,Y=[],[]
for i in range(len(x)):
    if end>=len(x):
        break
    X.append(x[i:end])
    Y.append(x[end])
    end+=1

In [10]:
print(f'X={X[0]},Y={Y[0]}')

X=[0, 1, 2],Y=3


In [35]:
import torch

In [37]:
X_tensor,Y_tensor=torch.tensor(X),torch.tensor(Y)

In [39]:
print(f"X Tensor:\n{X_tensor[:5]}\nY Tensor:\n{Y_tensor[:5]}")

X Tensor:
tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])
Y Tensor:
tensor([3, 4, 5, 6, 7])


In [51]:
X_tensor.shape

torch.Size([97, 3])

In [53]:
X_Shaped_tensor=X_tensor.reshape(97,3,1)
X_Shaped_tensor.shape

torch.Size([97, 3, 1])

In [57]:
help(torch.arange)

Help on built-in function arange in module torch:

arange(...)
    arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a 1-D tensor of size :math:`\left\lceil \frac{\text{end} - \text{start}}{\text{step}} \right\rceil`
    with values from the interval ``[start, end)`` taken with common difference
    :attr:`step` beginning from `start`.
    
    Note that non-integer :attr:`step` is subject to floating point rounding errors when
    comparing against :attr:`end`; to avoid inconsistency, we advise adding a small epsilon to :attr:`end`
    in such cases.
    
    .. math::
        \text{out}_{{i+1}} = \text{out}_{i} + \text{step}
    
    Args:
        start (Number): the starting value for the set of points. Default: ``0``.
        end (Number): the ending value for the set of points
        step (Number): the gap between each pair of adjacent points. Default: ``1``.
    
    Keyword args:
        out 

In [59]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
torch.zeros(100)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])

In [69]:
help(torch.binomial)

Help on built-in function binomial in module torch:

binomial(...)



In [76]:
import torch

import warnings
warnings.filterwarnings('ignore')

# Define the probability of success for each trial
prob = torch.tensor([0.5, 0.3, 0.8], dtype=torch.float32)

# Define the number of trials as a tensor
n = torch.tensor(100, dtype=torch.float32)

# Generate random numbers from a binomial distribution
samples = torch.binomial(n, prob)

print(samples)


tensor([50., 33., 82.])
